# This file is part of OpenScan-Hardware
# Copyright 2023 OpenScan Contributors
# SPDX-License-Identifier: CC-BY-SA-4.0

name: build-and-publish

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  book:
    concurrency:
      group: publish-gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Lint
        uses: pre-commit/action@v3.0.0
      - name: Install tools
        run: |
          python -m pip install --user --upgrade pip setuptools
          python -m pip install --user -r book/requirements.txt
      - name: Build book
        run: |
          jupyter-book build book
      - name: Publish to gh-pages
        if: >-
          github.repository == 'openscan-lsm/OpenScan-Hardware' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_build/html
          commit_message: Deploy book
